export function createEmptyAuctionRecord() {
  return {
    auctionId: null,
    assetFingerprint: null,
    source: null,
    titleRaw: null,
    addressRaw: null,
    community: null,
    road: null,
    laneNumber: null,
    buildingRoom: null,
    priceText: null,
    priceWan: null,
    valuationText: null,
    valuationWan: null,
    discountRate: null,
    startTime: null,
    endTime: null,
    status: null,
    signupCount: null,
    watchCount: null,
    court: null,
    isSold: false,
    soldPriceWan: null,
    bidderCount: null,
    originalUrl: null,
    normalizedUrl: null,
    riskKeywords: [],
    capturedAt: null,
    scriptVersion: null,
    runtime: null,
    parseWarnings: []
  };
}
